(define-module (ccc terraform)
  #:use-module (guix build utils)
  #:use-module (guix git-download)
  #:use-module (gnu packages golang)
  #:use-module (guix build-system go)
  #:use-module (guix licenses)
  #:use-module (guix packages)
  #:use-module (guix build-system gnu)
  #:use-module (guix download))

;; (define-public terraform
;;   (package
;;     (name "terraform")
;;     (version "1.6.0")
;;     (source
;;      (origin
;;        (method git-fetch)
;;        (uri (git-reference
;;              (url "https://github.com/hashicorp/terraform")
;;              (commit (string-append "v" version))))
;;        (file-name (git-file-name name version))
;;        (sha256
;;         (base32 "1za07hg5z94p5gpb93w8ji6f3r7nv1f4fc5dm66irxm7s6162nj7"))))
;;     (build-system go-build-system)
;;     (arguments
;;      '(#:import-path "github.com/hashicorp/terraform"))
;;     (propagated-inputs `(("go-sigs-k8s-io-yaml" ,go-sigs-k8s-io-yaml)
;;                          ("go-sigs-k8s-io-structured-merge-diff-v4" ,go-sigs-k8s-io-structured-merge-diff-v4)
;;                          ("go-sigs-k8s-io-json" ,go-sigs-k8s-io-json)
;;                          ("go-k8s-io-kube-openapi" ,go-k8s-io-kube-openapi)
;;                          ("go-k8s-io-klog-v2" ,go-k8s-io-klog-v2)
;;                          ("go-gopkg-in-yaml-v3" ,go-gopkg-in-yaml-v3)
;;                          ("go-gopkg-in-yaml-v2" ,go-gopkg-in-yaml-v2)
;;                          ("go-gopkg-in-ini-v1" ,go-gopkg-in-ini-v1)
;;                          ("go-gopkg-in-inf-v0" ,go-gopkg-in-inf-v0)
;;                          ("go-google-golang-org-genproto-googleapis-rpc" ,go-google-golang-org-genproto-googleapis-rpc)
;;                          ("go-google-golang-org-genproto-googleapis-api" ,go-google-golang-org-genproto-googleapis-api)
;;                          ("go-google-golang-org-appengine" ,go-google-golang-org-appengine)
;;                          ("go-golang-org-x-xerrors" ,go-golang-org-x-xerrors)
;;                          ("go-golang-org-x-time" ,go-golang-org-x-time)
;;                          ("go-golang-org-x-sync" ,go-golang-org-x-sync)
;;                          ("go-golang-org-x-exp-typeparams" ,go-golang-org-x-exp-typeparams)
;;                          ("go-go-opentelemetry-io-proto-otlp" ,go-go-opentelemetry-io-proto-otlp)
;;                          ("go-go-opentelemetry-io-otel-metric" ,go-go-opentelemetry-io-otel-metric)
;;                          ("go-go-opentelemetry-io-otel-exporters-otlp-otlptrace-otlptracehttp" ,go-go-opentelemetry-io-otel-exporters-otlp-otlptrace-otlptracehttp)
;;                          ("go-go-opentelemetry-io-otel-exporters-otlp-otlptrace-otlptracegrpc" ,go-go-opentelemetry-io-otel-exporters-otlp-otlptrace-otlptracegrpc)
;;                          ("go-go-opentelemetry-io-otel-exporters-otlp-otlptrace" ,go-go-opentelemetry-io-otel-exporters-otlp-otlptrace)
;;                          ("go-go-opentelemetry-io-otel-exporters-otlp-internal-retry" ,go-go-opentelemetry-io-otel-exporters-otlp-internal-retry)
;;                          ("go-go-opencensus-io" ,go-go-opencensus-io)
;;                          ("go-go-mongodb-org-mongo-driver" ,go-go-mongodb-org-mongo-driver)
;;                          ("go-github-com-vmihailenco-tagparser-v2" ,go-github-com-vmihailenco-tagparser-v2)
;;                          ("go-github-com-vmihailenco-msgpack-v5" ,go-github-com-vmihailenco-msgpack-v5)
;;                          ("go-github-com-ulikunitz-xz" ,go-github-com-ulikunitz-xz)
;;                          ("go-github-com-thlib-go-timezone-local" ,go-github-com-thlib-go-timezone-local)
;;                          ("go-github-com-thanhpk-randstr" ,go-github-com-thanhpk-randstr)
;;                          ("go-github-com-spf13-pflag" ,go-github-com-spf13-pflag)
;;                          ("go-github-com-spf13-cobra" ,go-github-com-spf13-cobra)
;;                          ("go-github-com-spf13-cast" ,go-github-com-spf13-cast)
;;                          ("go-github-com-shopspring-decimal" ,go-github-com-shopspring-decimal)
;;                          ("go-github-com-sergi-go-diff" ,go-github-com-sergi-go-diff)
;;                          ("go-github-com-satori-go-uuid" ,go-github-com-satori-go-uuid)
;;                          ("go-github-com-samber-lo" ,go-github-com-samber-lo)
;;                          ("go-github-com-rivo-uniseg" ,go-github-com-rivo-uniseg)
;;                          ("go-github-com-oklog-ulid" ,go-github-com-oklog-ulid)
;;                          ("go-github-com-oklog-run" ,go-github-com-oklog-run)
;;                          ("go-github-com-nu7hatch-gouuid" ,go-github-com-nu7hatch-gouuid)
;;                          ("go-github-com-munnerz-goautoneg" ,go-github-com-munnerz-goautoneg)
;;                          ("go-github-com-muesli-termenv" ,go-github-com-muesli-termenv)
;;                          ("go-github-com-mozillazg-go-httpheader" ,go-github-com-mozillazg-go-httpheader)
;;                          ("go-github-com-modern-go-reflect2" ,go-github-com-modern-go-reflect2)
;;                          ("go-github-com-modern-go-concurrent" ,go-github-com-modern-go-concurrent)
;;                          ("go-github-com-mitchellh-iochan" ,go-github-com-mitchellh-iochan)
;;                          ("go-github-com-mitchellh-go-testing-interface" ,go-github-com-mitchellh-go-testing-interface)
;;                          ("go-github-com-mgutz-ansi" ,go-github-com-mgutz-ansi)
;;                          ("go-github-com-mergestat-timediff" ,go-github-com-mergestat-timediff)
;;                          ("go-github-com-mattn-go-runewidth" ,go-github-com-mattn-go-runewidth)
;;                          ("go-github-com-mattn-go-colorable" ,go-github-com-mattn-go-colorable)
;;                          ("go-github-com-masterzen-simplexml" ,go-github-com-masterzen-simplexml)
;;                          ("go-github-com-manicminer-hamilton-autorest" ,go-github-com-manicminer-hamilton-autorest)
;;                          ("go-github-com-mailru-easyjson" ,go-github-com-mailru-easyjson)
;;                          ("go-github-com-lucasb-eyer-go-colorful" ,go-github-com-lucasb-eyer-go-colorful)
;;                          ("go-github-com-knadh-koanf" ,go-github-com-knadh-koanf)
;;                          ("go-github-com-klauspost-compress" ,go-github-com-klauspost-compress)
;;                          ("go-github-com-kballard-go-shellquote" ,go-github-com-kballard-go-shellquote)
;;                          ("go-github-com-json-iterator-go" ,go-github-com-json-iterator-go)
;;                          ("go-github-com-josharian-intern" ,go-github-com-josharian-intern)
;;                          ("go-github-com-joho-godotenv" ,go-github-com-joho-godotenv)
;;                          ("go-github-com-jedib0t-go-pretty-v6" ,go-github-com-jedib0t-go-pretty-v6)
;;                          ("go-github-com-jedib0t-go-pretty" ,go-github-com-jedib0t-go-pretty)
;;                          ("go-github-com-inconshreveable-mousetrap" ,go-github-com-inconshreveable-mousetrap)
;;                          ("go-github-com-imdario-mergo" ,go-github-com-imdario-mergo)
;;                          ("go-github-com-huandu-xstrings" ,go-github-com-huandu-xstrings)
;;                          ("go-github-com-henvic-httpretty" ,go-github-com-henvic-httpretty)
;;                          ("go-github-com-hashicorp-yamux" ,go-github-com-hashicorp-yamux)
;;                          ("go-github-com-hashicorp-terraform-plugin-log" ,go-github-com-hashicorp-terraform-plugin-log)
;;                          ("go-github-com-hashicorp-serf" ,go-github-com-hashicorp-serf)
;;                          ("go-github-com-hashicorp-golang-lru" ,go-github-com-hashicorp-golang-lru)
;;                          ("go-github-com-hashicorp-go-slug" ,go-github-com-hashicorp-go-slug)
;;                          ("go-github-com-hashicorp-go-safetemp" ,go-github-com-hashicorp-go-safetemp)
;;                          ("go-github-com-hashicorp-go-rootcerts" ,go-github-com-hashicorp-go-rootcerts)
;;                          ("go-github-com-hashicorp-go-msgpack" ,go-github-com-hashicorp-go-msgpack)
;;                          ("go-github-com-hashicorp-go-immutable-radix" ,go-github-com-hashicorp-go-immutable-radix)
;;                          ("go-github-com-grpc-ecosystem-grpc-gateway-v2" ,go-github-com-grpc-ecosystem-grpc-gateway-v2)
;;                          ("go-github-com-googleapis-gax-go-v2" ,go-github-com-googleapis-gax-go-v2)
;;                          ("go-github-com-googleapis-enterprise-certificate-proxy" ,go-github-com-googleapis-enterprise-certificate-proxy)
;;                          ("go-github-com-google-gofuzz" ,go-github-com-google-gofuzz)
;;                          ("go-github-com-google-go-querystring" ,go-github-com-google-go-querystring)
;;                          ("go-github-com-google-go-github-v45" ,go-github-com-google-go-github-v45)
;;                          ("go-github-com-google-gnostic" ,go-github-com-google-gnostic)
;;                          ("go-github-com-golang-protobuf" ,go-github-com-golang-protobuf)
;;                          ("go-github-com-golang-groupcache" ,go-github-com-golang-groupcache)
;;                          ("go-github-com-golang-jwt-jwt-v4" ,go-github-com-golang-jwt-jwt-v4)
;;                          ("go-github-com-gogo-protobuf" ,go-github-com-gogo-protobuf)
;;                          ("go-github-com-gofrs-uuid" ,go-github-com-gofrs-uuid)
;;                          ("go-github-com-go-openapi-swag" ,go-github-com-go-openapi-swag)
;;                          ("go-github-com-go-openapi-strfmt" ,go-github-com-go-openapi-strfmt)
;;                          ("go-github-com-go-openapi-jsonreference" ,go-github-com-go-openapi-jsonreference)
;;                          ("go-github-com-go-openapi-jsonpointer" ,go-github-com-go-openapi-jsonpointer)
;;                          ("go-github-com-go-openapi-errors" ,go-github-com-go-openapi-errors)
;;                          ("go-github-com-go-logr-stdr" ,go-github-com-go-logr-stdr)
;;                          ("go-github-com-go-logr-logr" ,go-github-com-go-logr-logr)
;;                          ("go-github-com-fsnotify-fsnotify" ,go-github-com-fsnotify-fsnotify)
;;                          ("go-github-com-fatih-color" ,go-github-com-fatih-color)
;;                          ("go-github-com-emicklei-go-restful-v3" ,go-github-com-emicklei-go-restful-v3)
;;                          ("go-github-com-dylanmei-iso8601" ,go-github-com-dylanmei-iso8601)
;;                          ("go-github-com-dimchansky-utfbom" ,go-github-com-dimchansky-utfbom)
;;                          ("go-github-com-creack-pty" ,go-github-com-creack-pty)
;;                          ("go-github-com-coreos-go-systemd" ,go-github-com-coreos-go-systemd)
;;                          ("go-github-com-cloudflare-circl" ,go-github-com-cloudflare-circl)
;;                          ("go-github-com-cli-shurcool-graphql" ,go-github-com-cli-shurcool-graphql)
;;                          ("go-github-com-cli-safeexec" ,go-github-com-cli-safeexec)
;;                          ("go-github-com-cli-go-gh" ,go-github-com-cli-go-gh)
;;                          ("go-github-com-clbanning-mxj" ,go-github-com-clbanning-mxj)
;;                          ("go-github-com-cenkalti-backoff-v4" ,go-github-com-cenkalti-backoff-v4)
;;                          ("go-github-com-bradleyfalzon-ghinstallation-v2" ,go-github-com-bradleyfalzon-ghinstallation-v2)
;;                          ("go-github-com-bmatcuk-doublestar-v4" ,go-github-com-bmatcuk-doublestar-v4)
;;                          ("go-github-com-bgentry-go-netrc" ,go-github-com-bgentry-go-netrc)
;;                          ("go-github-com-baiyubin-aliyun-sts-go-sdk" ,go-github-com-baiyubin-aliyun-sts-go-sdk)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-sts" ,go-github-com-aws-aws-sdk-go-v2-service-sts)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-ssooidc" ,go-github-com-aws-aws-sdk-go-v2-service-ssooidc)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-sso" ,go-github-com-aws-aws-sdk-go-v2-service-sso)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-internal-s3shared" ,go-github-com-aws-aws-sdk-go-v2-service-internal-s3shared)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-internal-presigned-url" ,go-github-com-aws-aws-sdk-go-v2-service-internal-presigned-url)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-internal-endpoint-discovery" ,go-github-com-aws-aws-sdk-go-v2-service-internal-endpoint-discovery)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-internal-checksum" ,go-github-com-aws-aws-sdk-go-v2-service-internal-checksum)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-internal-accept-encoding" ,go-github-com-aws-aws-sdk-go-v2-service-internal-accept-encoding)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-iam" ,go-github-com-aws-aws-sdk-go-v2-service-iam)
;;                          ("go-github-com-aws-aws-sdk-go-v2-internal-v4a" ,go-github-com-aws-aws-sdk-go-v2-internal-v4a)
;;                          ("go-github-com-aws-aws-sdk-go-v2-internal-ini" ,go-github-com-aws-aws-sdk-go-v2-internal-ini)
;;                          ("go-github-com-aws-aws-sdk-go-v2-internal-endpoints-v2" ,go-github-com-aws-aws-sdk-go-v2-internal-endpoints-v2)
;;                          ("go-github-com-aws-aws-sdk-go-v2-internal-configsources" ,go-github-com-aws-aws-sdk-go-v2-internal-configsources)
;;                          ("go-github-com-aws-aws-sdk-go-v2-credentials" ,go-github-com-aws-aws-sdk-go-v2-credentials)
;;                          ("go-github-com-aws-aws-sdk-go-v2-config" ,go-github-com-aws-aws-sdk-go-v2-config)
;;                          ("go-github-com-aws-aws-sdk-go-v2-aws-protocol-eventstream" ,go-github-com-aws-aws-sdk-go-v2-aws-protocol-eventstream)
;;                          ("go-github-com-aws-aws-sdk-go" ,go-github-com-aws-aws-sdk-go)
;;                          ("go-github-com-asaskevich-govalidator" ,go-github-com-asaskevich-govalidator)
;;                          ("go-github-com-armon-go-radix" ,go-github-com-armon-go-radix)
;;                          ("go-github-com-armon-go-metrics" ,go-github-com-armon-go-metrics)
;;                          ("go-github-com-apparentlymart-go-textseg-v15" ,go-github-com-apparentlymart-go-textseg-v15)
;;                          ("go-github-com-antchfx-xpath" ,go-github-com-antchfx-xpath)
;;                          ("go-github-com-antchfx-xmlquery" ,go-github-com-antchfx-xmlquery)
;;                          ("go-github-com-puerkitobio-urlesc" ,go-github-com-puerkitobio-urlesc)
;;                          ("go-github-com-puerkitobio-purell" ,go-github-com-puerkitobio-purell)
;;                          ("go-github-com-microsoft-go-winio" ,go-github-com-microsoft-go-winio)
;;                          ("go-github-com-masterminds-sprig-v3" ,go-github-com-masterminds-sprig-v3)
;;                          ("go-github-com-masterminds-semver-v3" ,go-github-com-masterminds-semver-v3)
;;                          ("go-github-com-masterminds-goutils" ,go-github-com-masterminds-goutils)
;;                          ("go-github-com-christrenkamp-goxpath" ,go-github-com-christrenkamp-goxpath)
;;                          ("go-github-com-burntsushi-toml" ,go-github-com-burntsushi-toml)
;;                          ("go-github-com-azure-go-ntlmssp" ,go-github-com-azure-go-ntlmssp)
;;                          ("go-github-com-azure-go-autorest-tracing" ,go-github-com-azure-go-autorest-tracing)
;;                          ("go-github-com-azure-go-autorest-logger" ,go-github-com-azure-go-autorest-logger)
;;                          ("go-github-com-azure-go-autorest-autorest-validation" ,go-github-com-azure-go-autorest-autorest-validation)
;;                          ("go-github-com-azure-go-autorest-autorest-to" ,go-github-com-azure-go-autorest-autorest-to)
;;                          ("go-github-com-azure-go-autorest-autorest-date" ,go-github-com-azure-go-autorest-autorest-date)
;;                          ("go-github-com-azure-go-autorest-autorest-azure-cli" ,go-github-com-azure-go-autorest-autorest-azure-cli)
;;                          ("go-github-com-azure-go-autorest-autorest-adal" ,go-github-com-azure-go-autorest-autorest-adal)
;;                          ("go-github-com-azure-go-autorest" ,go-github-com-azure-go-autorest)
;;                          ("go-github-com-alecaivazis-survey-v2" ,go-github-com-alecaivazis-survey-v2)
;;                          ("go-cloud-google-com-go-iam" ,go-cloud-google-com-go-iam)
;;                          ("go-cloud-google-com-go-compute-metadata" ,go-cloud-google-com-go-compute-metadata)
;;                          ("go-cloud-google-com-go-compute" ,go-cloud-google-com-go-compute)
;;                          ("go-cloud-google-com-go" ,go-cloud-google-com-go)
;;                          ("go-k8s-io-utils" ,go-k8s-io-utils)
;;                          ("go-k8s-io-client-go" ,go-k8s-io-client-go)
;;                          ("go-k8s-io-apimachinery" ,go-k8s-io-apimachinery)
;;                          ("go-k8s-io-api" ,go-k8s-io-api)
;;                          ("go-honnef-co-go-tools" ,go-honnef-co-go-tools)
;;                          ("go-google-golang-org-protobuf" ,go-google-golang-org-protobuf)
;;                          ("go-google-golang-org-grpc-cmd-protoc-gen-go-grpc" ,go-google-golang-org-grpc-cmd-protoc-gen-go-grpc)
;;                          ("go-google-golang-org-grpc" ,go-google-golang-org-grpc)
;;                          ("go-google-golang-org-genproto" ,go-google-golang-org-genproto)
;;                          ("go-google-golang-org-api" ,go-google-golang-org-api)
;;                          ("go-golang-org-x-tools-cmd-cover" ,go-golang-org-x-tools-cmd-cover)
;;                          ("go-golang-org-x-tools" ,go-golang-org-x-tools)
;;                          ("go-golang-org-x-text" ,go-golang-org-x-text)
;;                          ("go-golang-org-x-term" ,go-golang-org-x-term)
;;                          ("go-golang-org-x-sys" ,go-golang-org-x-sys)
;;                          ("go-golang-org-x-oauth2" ,go-golang-org-x-oauth2)
;;                          ("go-golang-org-x-net" ,go-golang-org-x-net)
;;                          ("go-golang-org-x-mod" ,go-golang-org-x-mod)
;;                          ("go-golang-org-x-exp" ,go-golang-org-x-exp)
;;                          ("go-golang-org-x-crypto" ,go-golang-org-x-crypto)
;;                          ("go-go-opentelemetry-io-otel-trace" ,go-go-opentelemetry-io-otel-trace)
;;                          ("go-go-opentelemetry-io-otel-sdk" ,go-go-opentelemetry-io-otel-sdk)
;;                          ("go-go-opentelemetry-io-otel" ,go-go-opentelemetry-io-otel)
;;                          ("go-go-opentelemetry-io-contrib-exporters-autoexport" ,go-go-opentelemetry-io-contrib-exporters-autoexport)
;;                          ("go-github-com-zclconf-go-cty-yaml" ,go-github-com-zclconf-go-cty-yaml)
;;                          ("go-github-com-zclconf-go-cty-debug" ,go-github-com-zclconf-go-cty-debug)
;;                          ("go-github-com-zclconf-go-cty" ,go-github-com-zclconf-go-cty)
;;                          ("go-github-com-xlab-treeprint" ,go-github-com-xlab-treeprint)
;;                          ("go-github-com-xanzy-ssh-agent" ,go-github-com-xanzy-ssh-agent)
;;                          ("go-github-com-tombuildsstuff-giovanni" ,go-github-com-tombuildsstuff-giovanni)
;;                          ("go-github-com-tencentyun-cos-go-sdk-v5" ,go-github-com-tencentyun-cos-go-sdk-v5)
;;                          ("go-github-com-tencentcloud-tencentcloud-sdk-go-tencentcloud-tag" ,go-github-com-tencentcloud-tencentcloud-sdk-go-tencentcloud-tag)
;;                          ("go-github-com-tencentcloud-tencentcloud-sdk-go-tencentcloud-sts" ,go-github-com-tencentcloud-tencentcloud-sdk-go-tencentcloud-sts)
;;                          ("go-github-com-tencentcloud-tencentcloud-sdk-go-tencentcloud-common" ,go-github-com-tencentcloud-tencentcloud-sdk-go-tencentcloud-common)
;;                          ("go-github-com-spf13-afero" ,go-github-com-spf13-afero)
;;                          ("go-github-com-posener-complete" ,go-github-com-posener-complete)
;;                          ("go-github-com-pkg-errors" ,go-github-com-pkg-errors)
;;                          ("go-github-com-pkg-browser" ,go-github-com-pkg-browser)
;;                          ("go-github-com-packer-community-winrmcp" ,go-github-com-packer-community-winrmcp)
;;                          ("go-github-com-nishanths-exhaustive" ,go-github-com-nishanths-exhaustive)
;;                          ("go-github-com-mitchellh-reflectwalk" ,go-github-com-mitchellh-reflectwalk)
;;                          ("go-github-com-mitchellh-mapstructure" ,go-github-com-mitchellh-mapstructure)
;;                          ("go-github-com-mitchellh-gox" ,go-github-com-mitchellh-gox)
;;                          ("go-github-com-mitchellh-go-wordwrap" ,go-github-com-mitchellh-go-wordwrap)
;;                          ("go-github-com-mitchellh-go-linereader" ,go-github-com-mitchellh-go-linereader)
;;                          ("go-github-com-mitchellh-go-homedir" ,go-github-com-mitchellh-go-homedir)
;;                          ("go-github-com-mitchellh-copystructure" ,go-github-com-mitchellh-copystructure)
;;                          ("go-github-com-mitchellh-colorstring" ,go-github-com-mitchellh-colorstring)
;;                          ("go-github-com-mitchellh-cli" ,go-github-com-mitchellh-cli)
;;                          ("go-github-com-mattn-go-shellwords" ,go-github-com-mattn-go-shellwords)
;;                          ("go-github-com-mattn-go-isatty" ,go-github-com-mattn-go-isatty)
;;                          ("go-github-com-masterzen-winrm" ,go-github-com-masterzen-winrm)
;;                          ("go-github-com-manicminer-hamilton" ,go-github-com-manicminer-hamilton)
;;                          ("go-github-com-lib-pq" ,go-github-com-lib-pq)
;;                          ("go-github-com-kardianos-osext" ,go-github-com-kardianos-osext)
;;                          ("go-github-com-jmespath-go-jmespath" ,go-github-com-jmespath-go-jmespath)
;;                          ("go-github-com-hashicorp-terraform-svchost" ,go-github-com-hashicorp-terraform-svchost)
;;                          ("go-github-com-hashicorp-terraform-registry-address" ,go-github-com-hashicorp-terraform-registry-address)
;;                          ("go-github-com-hashicorp-jsonapi" ,go-github-com-hashicorp-jsonapi)
;;                          ("go-github-com-hashicorp-hcl-v2" ,go-github-com-hashicorp-hcl-v2)
;;                          ("go-github-com-hashicorp-hcl" ,go-github-com-hashicorp-hcl)
;;                          ("go-github-com-hashicorp-go-version" ,go-github-com-hashicorp-go-version)
;;                          ("go-github-com-hashicorp-go-uuid" ,go-github-com-hashicorp-go-uuid)
;;                          ("go-github-com-hashicorp-go-tfe" ,go-github-com-hashicorp-go-tfe)
;;                          ("go-github-com-hashicorp-go-retryablehttp" ,go-github-com-hashicorp-go-retryablehttp)
;;                          ("go-github-com-hashicorp-go-plugin" ,go-github-com-hashicorp-go-plugin)
;;                          ("go-github-com-hashicorp-go-multierror" ,go-github-com-hashicorp-go-multierror)
;;                          ("go-github-com-hashicorp-go-hclog" ,go-github-com-hashicorp-go-hclog)
;;                          ("go-github-com-hashicorp-go-getter" ,go-github-com-hashicorp-go-getter)
;;                          ("go-github-com-hashicorp-go-cleanhttp" ,go-github-com-hashicorp-go-cleanhttp)
;;                          ("go-github-com-hashicorp-go-checkpoint" ,go-github-com-hashicorp-go-checkpoint)
;;                          ("go-github-com-hashicorp-go-azure-helpers" ,go-github-com-hashicorp-go-azure-helpers)
;;                          ("go-github-com-hashicorp-errwrap" ,go-github-com-hashicorp-errwrap)
;;                          ("go-github-com-hashicorp-copywrite" ,go-github-com-hashicorp-copywrite)
;;                          ("go-github-com-hashicorp-consul-sdk" ,go-github-com-hashicorp-consul-sdk)
;;                          ("go-github-com-hashicorp-consul-api" ,go-github-com-hashicorp-consul-api)
;;                          ("go-github-com-hashicorp-aws-sdk-go-base-v2" ,go-github-com-hashicorp-aws-sdk-go-base-v2)
;;                          ("go-github-com-google-uuid" ,go-github-com-google-uuid)
;;                          ("go-github-com-google-go-cmp" ,go-github-com-google-go-cmp)
;;                          ("go-github-com-golang-mock" ,go-github-com-golang-mock)
;;                          ("go-github-com-go-test-deep" ,go-github-com-go-test-deep)
;;                          ("go-github-com-dylanmei-winrmtest" ,go-github-com-dylanmei-winrmtest)
;;                          ("go-github-com-davecgh-go-spew" ,go-github-com-davecgh-go-spew)
;;                          ("go-github-com-coreos-pkg" ,go-github-com-coreos-pkg)
;;                          ("go-github-com-chzyer-readline" ,go-github-com-chzyer-readline)
;;                          ("go-github-com-bmatcuk-doublestar" ,go-github-com-bmatcuk-doublestar)
;;                          ("go-github-com-bgentry-speakeasy" ,go-github-com-bgentry-speakeasy)
;;                          ("go-github-com-aws-smithy-go" ,go-github-com-aws-smithy-go)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-s3" ,go-github-com-aws-aws-sdk-go-v2-service-s3)
;;                          ("go-github-com-aws-aws-sdk-go-v2-service-dynamodb" ,go-github-com-aws-aws-sdk-go-v2-service-dynamodb)
;;                          ("go-github-com-aws-aws-sdk-go-v2-feature-s3-manager" ,go-github-com-aws-aws-sdk-go-v2-feature-s3-manager)
;;                          ("go-github-com-aws-aws-sdk-go-v2-feature-ec2-imds" ,go-github-com-aws-aws-sdk-go-v2-feature-ec2-imds)
;;                          ("go-github-com-aws-aws-sdk-go-v2" ,go-github-com-aws-aws-sdk-go-v2)
;;                          ("go-github-com-armon-circbuf" ,go-github-com-armon-circbuf)
;;                          ("go-github-com-apparentlymart-go-versions" ,go-github-com-apparentlymart-go-versions)
;;                          ("go-github-com-apparentlymart-go-userdirs" ,go-github-com-apparentlymart-go-userdirs)
;;                          ("go-github-com-apparentlymart-go-shquot" ,go-github-com-apparentlymart-go-shquot)
;;                          ("go-github-com-apparentlymart-go-dump" ,go-github-com-apparentlymart-go-dump)
;;                          ("go-github-com-apparentlymart-go-cidr" ,go-github-com-apparentlymart-go-cidr)
;;                          ("go-github-com-aliyun-aliyun-tablestore-go-sdk" ,go-github-com-aliyun-aliyun-tablestore-go-sdk)
;;                          ("go-github-com-aliyun-aliyun-oss-go-sdk" ,go-github-com-aliyun-aliyun-oss-go-sdk)
;;                          ("go-github-com-aliyun-alibaba-cloud-sdk-go" ,go-github-com-aliyun-alibaba-cloud-sdk-go)
;;                          ("go-github-com-agext-levenshtein" ,go-github-com-agext-levenshtein)
;;                          ("go-github-com-protonmail-go-crypto" ,go-github-com-protonmail-go-crypto)
;;                          ("go-github-com-netflix-go-expect" ,go-github-com-netflix-go-expect)
;;                          ("go-github-com-azure-go-autorest-autorest" ,go-github-com-azure-go-autorest-autorest)
;;                          ("go-github-com-azure-azure-sdk-for-go" ,go-github-com-azure-azure-sdk-for-go)
;;                          ("go-cloud-google-com-go-storage" ,go-cloud-google-com-go-storage)
;;                          ("go-cloud-google-com-go-kms" ,go-cloud-google-com-go-kms)))
;;     (home-page "https://github.com/hashicorp/terraform")
;;     (synopsis #f)
;;     (description #f)
;;     (license #f)))
;; (define-public go-github-com-modern-go-reflect2
;;   (package
;;     (name "go-github-com-modern-go-reflect2")
;;     (version "1.0.2")
;;     (source
;;      (origin
;;        (method git-fetch)
;;        (uri (git-reference
;;              (url "https://github.com/modern-go/reflect2")
;;              (commit (string-append "v" version))))
;;        (file-name (git-file-name name version))
;;        (sha256
;;         (base32 "05a89f9j4nj8v1bchfkv2sy8piz746ikj831ilbp54g8dqhl8vzr"))))
;;     (build-system go-build-system)
;;     (arguments
;;      '(#:import-path "github.com/modern-go/reflect2"))
;;     (home-page "https://github.com/modern-go/reflect2")
;;     (synopsis "reflect2")
;;     (description "reflect api that avoids runtime reflect.Value cost")
;;     (license asl2.0)))

;; (define-public go-github-com-json-iterator-go
;;   (package
;;     (name "go-github-com-json-iterator-go")
;;     (version "1.1.12")
;;     (source
;;      (origin
;;        (method git-fetch)
;;        (uri (git-reference
;;              (url "https://github.com/json-iterator/go")
;;              (commit (string-append "v" version))))
;;        (file-name (git-file-name name version))
;;        (sha256
;;         (base32 "1c8f0hxm18wivx31bs615x3vxs2j3ba0v6vxchsjhldc8kl311bz"))))
;;     (build-system go-build-system)
;;     (arguments
;;      '(#:import-path "github.com/json-iterator/go"))
;;     (propagated-inputs `(("go-github-com-stretchr-testify" ,go-github-com-stretchr-testify)
;;                          ("go-github-com-modern-go-reflect2" ,go-github-com-modern-go-reflect2)
;;                          ("go-github-com-modern-go-concurrent" ,go-github-com-modern-go-concurrent)
;;                          ("go-github-com-google-gofuzz" ,go-github-com-google-gofuzz)
;;                          ("go-github-com-davecgh-go-spew" ,go-github-com-davecgh-go-spew)))
;;     (home-page "https://github.com/json-iterator/go")
;;     (synopsis "Benchmark")
;;     (description
;;      "Package jsoniter implements encoding and decoding of JSON as defined in
;; @@url{https://rfc-editor.org/rfc/rfc4627.html,RFC 4627} and provides interfaces
;; with identical syntax of standard lib encoding/json.  Converting from
;; encoding/json to jsoniter is no more than replacing the package with jsoniter
;; and variable type declarations (if any).  jsoniter interfaces gives 100%
;; compatibility with code using standard lib.")
;;     (license expat)))
;; (define-public go-github-com-modern-go-concurrent
;;   (package
;;     (name "go-github-com-modern-go-concurrent")
;;     (version "0.0.0-20180306012644-bacd9c7ef1dd")
;;     (source
;;      (origin
;;        (method git-fetch)
;;        (uri (git-reference
;;              (url "https://github.com/modern-go/concurrent")
;;              (commit (go-version->git-ref version))))
;;        (file-name (git-file-name name version))
;;        (sha256
;;         (base32 "0s0fxccsyb8icjmiym5k7prcqx36hvgdwl588y0491gi18k5i4zs"))))
;;     (build-system go-build-system)
;;     (arguments
;;      '(#:import-path "github.com/modern-go/concurrent"))
;;     (home-page "https://github.com/modern-go/concurrent")
;;     (synopsis "concurrent")
;;     (description
;;      "because sync.Map is only available in go 1.9, we can use concurrent.Map to make
;; code portable")
;;     (license asl2.0)))

;; (define-public go-sigs-k8s-io-structured-merge-diff-v4
;;   (package
;;     (name "go-sigs-k8s-io-structured-merge-diff-v4")
;;     (version "4.2.3")
;;     (source
;;      (origin
;;        (method git-fetch)
;;        (uri (git-reference
;;              (url "https://github.com/kubernetes-sigs/structured-merge-diff")
;;              (commit (string-append "v" version))))
;;        (file-name (git-file-name name version))
;;        (sha256
;;         (base32 "02db3a0ln64fv8s7lis7jnsprphxbr33cspxb0kdw9l9zy8dg45k"))))
;;     (build-system go-build-system)
;;     (arguments
;;      '(#:import-path "sigs.k8s.io/structured-merge-diff/v4"
;;        #:unpack-path "sigs.k8s.io/structured-merge-diff/v4"))
;;     (propagated-inputs `(("go-github-com-modern-go-concurrent" ,go-github-com-modern-go-concurrent)
;;                          ("go-github-com-json-iterator-go" ,go-github-com-json-iterator-go)
;;                          ("go-github-com-google-gofuzz" ,go-github-com-google-gofuzz)
;;                          ("go-gopkg-in-yaml-v2" ,go-gopkg-in-yaml-v2)))
;;     (home-page "https://sigs.k8s.io/structured-merge-diff/v4")
;;     (synopsis "Structured Merge and Diff")
;;     (description
;;      "This repo contains code which implements the Kubernetes \"apply\" operation.")
;;     (license asl2.0)))

;; (define-public go-sigs-k8s-io-json
;;   (package
;;    (name "go-sigs-k8s-io-json")
;;    (version "0.0.0-20220713155537-f223a00ba0e2")
;;    (source
;;     (origin
;;      (method git-fetch)
;;      (uri (git-reference
;;            (url "https://github.com/kubernetes-sigs/json")
;;            (commit (go-version->git-ref version))))
;;      (file-name (git-file-name name version))
;;      (sha256
;;       (base32 "1ykph9nqks2xif0fffpp5nbzp4r3c5pvgi1wrnwn7lxp1718g4jm"))))
;;    (build-system go-build-system)
;;    (arguments
;;     '(#:import-path "sigs.k8s.io/json"))
;;    (home-page "https://sigs.k8s.io/json")
;;    (synopsis "sigs.k8s.io/json")
;;    (description
;;     "This library is a subproject of
;; @@url{https://github.com/kubernetes/community/tree/master/sig-api-machinery#json,sig-api-machinery}.
;;  It provides case-sensitive, integer-preserving JSON unmarshaling functions
;; based on @@code{encoding/json} @@code{Unmarshal()}.")
;;    (license unlicense)
;;    ))
