(specifications->manifest
  '(
    ;;  Virtualization
    "qemu"
    "virt-manager"
    "libvirt"
    ;;  Fonts
    "font-linuxlibertine"
    "font-liberation"
    "font-victor-mono"
    "font-iosevka"
    "font-google-noto-emoji"
    ;;  Disk Utilities
    "gparted"
    "nvme-cli"
    "hdparm"
    "parted"
    "sdparm"
    "gptfdisk"
    ;; Monitoring
    "iotop"
    "sysstat"
    "smartmontools"
    "ncdu"
    "acpi"
    "lsof"
    "lshw"
    "dfc"
    ;;  Media
    "imv"
    "imagemagick"
    "ffmpeg"
    "pulsemixer"
    "mpv"
    "yt-dlp"
    "gallery-dl"
    "nerd-dictation"
    ;; Security
    "pinentry-qt"
    "pinentry-emacs"
    "password-store"
    "gnupg"
    ;; Xorg
    "xclip"
    "xdg-utils"
    "xmodmap"
    "alacritty"
    "xset"
    ;; File utils
    "fd"
    "visidata"
    "zip"
    "unzip"
    "eza"
    "ripgrep"
    "duplicity"
    "python-boto3"                      ; required by duplicity
    ;; Python
    "python-language-server"
    "python-pylint"
    "python-black"
    "python-pyls-black"
    "python-mypy"
    ;; Office
    "mupdf"
    "libreoffice"
    "ispell"
    "plantuml"
    "scribus"
    "offlineimap"
    "wordnet"
    ;; Network
    "nmap"
    "sshfs"
    "nfs-utils"
    "syncthing"
    "curl"
    "wget"
    "rsync"
    "tor"
    "i2pd"
    ;; Containers
    "docker"
    "docker-cli"
    "containerd"
    ;; X
    "picom"
    "feh"
    ;; This is needed for vertico-posframe to show on the correct monitor
    "xwininfo"
    ;;
    "libvterm" ;; This is needed to compile emacs-vterma
    "go"
    "ansible"
    "stow"
    "bpytop"
    "icecat"
    "nyxt"
    "pandoc"
    "awscli"
    "scrot"
    "ledger"
    "jq"
    "multipath-tools"
    "gcc"
    "k9s"))
