(specifications->manifest
  '(
    ;;  Virtualization
    "qemu"
    "virt-manager"
    "libvirt"
    ;;  Fonts
    "font-linuxlibertine"
    "font-liberation"
    "font-victor-mono"
    ;;  Disk Utilities
    "gparted"
    "nvme-cli"
    "hdparm"
    "parted"
    "sdparm"
    "gptfdisk"
    ;; Monitoring
    "iotop"
    "sysstat"
    "smartmontools"
    "ncdu"
    "acpi"
    "lsof"
    "lshw"
    ;;  Media
    "imv"
    "imagemagick"
    "ffmpeg"
    "pulsemixer"
    "mpv"
    "yt-dlp"
    "gallery-dl"
    "nerd-dictation"
    ;; Security
    "pinentry-qt"
    "pinentry-emacs"
    "password-store"
    "gnupg"
    ;; Xorg
    "xclip"
    "xdg-utils"
    "xmodmap"
    "alacritty"
    "xset"
    ;; File utils
    "zip"
    "unzip"
    "exa"
    "ripgrep"
    ;; Office
    "mupdf"
    "libreoffice"
    "ispell"
    "plantuml"
    "scribus"
    "offlineimap"
    "wordnet"
    ;; Network
    "nmap"
    "sshfs"
    "nfs-utils"
    "syncthing"
    "curl"
    "wget"
    "rsync"
    ;;
    "go"
    "stow"
    "bpytop"
    "icecat"
    "pandoc"
    "awscli"
    "scrot"
    "ledger"
    "jq"
    "multipath-tools"
    "gcc"
    "k9s"
    ))
