(define-module (ccc machines usb config)
  #:export (usb-os))
(use-modules (gnu)
             (gnu packages)
             (nongnu packages linux)
             (nongnu system linux-initrd))

(import (only (srfi srfi-1) remove))
(use-service-modules desktop networking xorg docker)

(define usb-os
  (operating-system
   (locale "en_US.utf8")
   (kernel linux)
   (initrd microcode-initrd)
   (firmware (list linux-firmware))
   (timezone "America/Los_Angeles")
   (keyboard-layout (keyboard-layout "us"))
   (host-name "usb")
   (users (cons* (user-account
                  (name "guest")
                  (password "root")
                  (group "users")
                  (home-directory "/home/guest")
                  (supplementary-groups
                   '("dialout" "wheel" "netdev" "audio" "video")))
                 %base-user-accounts))
   (packages
    (append
     (list (specification->package "emacs")
           (specification->package "emacs-exwm")
           (specification->package "emacs-pdf-tools")
           (specification->package "emacs-desktop-environment")
           (specification->package "xrandr")
           (specification->package "autorandr")
           (specification->package "pulseaudio")
           (specification->package "docker")
           (specification->package "fd")
           (specification->package "git")
           (specification->package "file")
           (specification->package "gnupg")
           (specification->package "password-store")
           (specification->package "duplicity")
           (specification->package "cryptsetup")
           (specification->package "rng-tools")
           (specification->package "pinentry-qt")
           (specification->package "wpa-supplicant-minimal")
           (specification->package "font-victor-mono")
           (specification->package "font-linuxlibertine")
           (specification->package "font-liberation")
           (specification->package "font-iosevka")
           (specification->package "font-google-noto-emoji")
           (specification->package "zfs")
           (specification->package "isc-dhcp")
           (specification->package "picom")

                                        ; Required by org-roam
           (specification->package "sqlite")

           ;;  User programs
           (specification->package "mpv")
           (specification->package "parted")
           (specification->package "gparted")
           (specification->package "ncdu")
           (specification->package "dfc")
           (specification->package "xset")
           (specification->package "zip")
           (specification->package "unzip")
           (specification->package "iotop")
           (specification->package "nmap")
           (specification->package "sshfs")
           (specification->package "icecat")
           (specification->package "xmodmap")
           (specification->package "ncurses")
           (specification->package "ripgrep")
           (specification->package "rsync")
           (specification->package "feh")
           (specification->package "libvterm")
           (specification->package "xwininfo")
           (specification->package "ansible")
           (specification->package "btop")
           (specification->package "gcc-toolchain")
           (specification->package "jq")
           (specification->package "wget")
           (specification->package "curl")
           (specification->package "ispell")
           (specification->package "lsof")
           (specification->package "net-tools")
           (specification->package "plantuml")
           (specification->package "jq")
           (specification->package "youtube-dl")
           (specification->package "gptfdisk")
           (specification->package "eza")
           (specification->package "alacritty")
           (specification->package "btrfs-progs")
           (specification->package "dosfstools")
           )
     %base-packages))
   (services
    (append
     (list (service gdm-service-type (gdm-configuration
                                      (auto-login? #t)
                                      (default-user "guest")
                                      (xorg-configuration (xorg-configuration (keyboard-layout keyboard-layout)))))
           )
     (remove (lambda (service) (eq? (service-kind service) gdm-service-type)) %desktop-services)))
   (sudoers-file (plain-file "sudoers" "\
root ALL=(ALL) ALL
%wheel ALL=(ALL) NOPASSWD:ALL\n"))
(bootloader (bootloader-configuration
             (bootloader grub-efi-bootloader)
             (targets '("/boot/efi"))))

   (file-systems
    (cons* (file-system
            (mount-point "/home")
            (device (file-system-label "Home"))
            (type "ext4"))
           %base-file-systems
           )
    )
   )
  )

usb-os
