#+TITLE: Makefile

* Snippets
:PROPERTIES:
:snippet_mode: make-mode
:header-args:  :tangle (get-snippet-path)
:END:
** phony
#+begin_src snippet
# name: phony
# key: phony
# --
.PHONY: $1
$1: ## $2
	@$0
#+end_src
